config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'groups#index'
  resources :groups, only: %i[index new create destroy show] do
    resources :entities, only: %i[index new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user, class_name: 'User', foreign_key: :user_id
    has_many :category_transactions
    has_many :transactions, through: :category_transactions
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
    belongs_to :transaction
    belongs_to :category
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :entity_group
  has_many :groups, through: :entity_group

  validates :name, presence: true, length: { in: 4..100 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/entity_group.rb
class EntityGroup < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :entity_group
  has_many :entities, through: :entity_group

  validates :name, presence: true, length: { in: 4..100 }
  validates :icon, presence: true, length: { in: 4..800 }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :author, class_name: 'User', foreign_key: :author_id
    has_many :category_transactions
    has_many :categories, through: :category_transactions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :entities, foreign_key: :author_id
  has_many :groups, foreign_key: :author_id

  validates :password, presence: true
  validates :email, presence: true
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :conifgure_parameters, if: :devise_controller?

  def conifgure_parameters
    attributes = %i[name email password]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  def index
    @group_by_user = current_user.groups.find(params[:group_id])
    @entities = @group_by_user.entities
  end

  def new
    @group = current_user.groups.find(params[:group_id])
    @entity = @group.entities.new
  end

  def create
    @group = current_user.groups.find(params[:group_id])
    @entity = current_user.entities.create(entity_params)
    if @entity.save
      @group_entity = @entity.entity_group.create(group_id: @group.id, entity_id: @entity.id)
      if @group_entity.save
        flash[:notice] = 'Transaction created successfully'
        redirect_to group_entities_path(@group)
      else
        flash.now[:alert] = 'Category creation failed'
        render action: 'new'
      end
    else
      flash.now[:alert] = 'Transaction creation failed, try again'
      render action: 'new'
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groupsController.rb
# frozen_string_literal: true

class GroupsController < ApplicationController # rubocop:todo Style/Documentation
  def index
    @group = Group.all
   end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(category_params)
    @group.author = current_user
    if @group.save
    redirect_to groups_path, notice: "#{@group.name} successfully created." if @group.save
    flash[:notice] = 'Inventory created successfully!'
    else
      flash.now[:alert] = 'Something unexpected happened, inventory could not be created.'
      render :new
    end
  end

  # private

  def category_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    if user_signed_in?
      @group = current_user.groups
    else
      render 'users/slash'
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @user = current_user
    @group = @user.groups.create(category_params)
    if @group.save
      flash[:notice] = 'Category created successfully'
      redirect_to groups_path
    else
      flash.now[:alert] = 'Failed try again'
      render action: 'new'
    end
  end

  private

  def category_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<div class="d-flex flex-column align-items-center">
  <h1>Add new category</h1>
  <%= form_with model: @category, url: new_category_path,class: "d-flex flex-column", method: :post do |form| %>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
    <%= form.label :icon, 'Icon' %>
    <%= form.text_field :icon %>
 
    <%= form.submit 'Add Category' %>
  <% end %>
</div>

app/views/entities/index.html.erb
 <%= render partial: "shared/entity_nav" %>
  <br />
 <section class="entity_section">
 <div class="group_container">
            <div class="Group__image">
            <img src= <%= @group_by_user.icon %>  alt="Logo" />
            </div>
            <div class="Group__text">
             <%= link_to @group_by_user.name, class: "nav-link" %>
            </div>
            <div class="Group__price">
           
            </div>
</div>
<div class="group__text">
<p>short loin jerky chuck pork belly pork. Turducken kielbasa chicken 
andouille t-bone picanha. Flank ham hock 
prosciutto ground round ball tip picanha.
</p>
<div>

<% if @entities.count > 0 %>
  <% @entities.each do |entity| %>
 <div class="sub_nav2">
        <div>
            <p><b><%= entity.name %></b></p>
            <p><%= l entity.created_at, format: :long %></p>
        </div>
          <p class="Group_price">
            $<%= entity.amount %>
        </p>
</div>
  <% end %>
<% else %>
  <p>You have no Transactions yet</p>
<% end %>

 <div class="sub_nav">
        <p>Total payment</p>
        <p><b><%=  @entities.map(&:amount).sum %></b></p>
</div>
<%= link_to 'Add Transaction', new_group_entity_path, class: "add_transaction" %>
</section>

app/views/entities/new.html.erb
 <%= render partial: "shared/entity_nav" %>
<div class="d-flex flex-column align-items-center">
  <h1>Add new entity</h1>
  <%= form_with model: @entity, url:  group_entities_path,class: "d-flex flex-column", method: :post do |form| %>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
    <%= form.label :amount, 'Amount' %>
    <%= form.number_field :amount %>
    <%= form.submit 'Add Entities' %>
  <% end %>
</div>

app/views/groups/index.html.erb
 
 <%= render partial: "shared/popup" %>
 <%= render partial: "shared/navbar" %>
<main>
    <div class="sub_nav">
        <p>Gifted</p>
        <p><b><%= link_to 'New category', new_group_path, class: "new_category" %>
</b></p>
    </div>

    <div class="main__section">

    <% @group.each do |grp| %>

   
        <div class="group_container">
            <div class="Group__image">
            <img src=<%= grp.icon %> alt="Logo" />
            </div>
            <div class="Group__text">
             <%= link_to grp.name,  group_entities_path(grp.id), class: "nav-link" %>
                <p><%= l grp.created_at, format: :short %></p>
            </div>
            <div class="Group__price">
            <p><b>$ <%= grp.entities.sum(&:amount) %></b></p>
            </div>
        </div>

    <% end %>
    </div>
    <div class="scan">
    <button class="scan_btn">Scan</button>
    </div>
</main>

app/views/groups/new.html.erb
 <%= render partial: "shared/entity_nav" %>
 <br />
<div class="d-flex flex-column align-items-center">
  <h1>Add new category</h1>
  <%= form_with model: @group, url:  groups_path, class: "d-flex flex-column", method: :post do |form| %>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
    <%= form.label :icon, 'Icon' %>
    <%= form.text_field :icon %>
    <%= form.submit 'Add Category' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,400i|Nunito:300,300i" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=EB+Garamond:ital,wght@1,800&display=swap" rel="stylesheet">
  </head>

  <body>
  <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_entity_nav.html.erb
<header class = "header">   
    <nav class = "nav_container">
            <%= link_to groups_path do %>
                <div nav__icon>
                    <i class="fa-solid fa-arrow-left white"></i>
                </div>
            <% end %>
        
            <div class="nav__text">
                <p>Transactions</p>
            </div>
            <div class="nav__text">
         
            </div>
    </nav>
</header>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div  role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div  role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header class = "header">   
    <nav class = "nav_container" id="nav_btn">
            <div class="nav__icon">
                <i class="fa-solid fa-bars"></i>
            </div>
            <div class="nav__text">
                <p>Transactions</p>
            </div>
            <div class="nav__text">
            <i class="fa-solid fa-magnifying-glass"></i>
            </div>
    </nav>
    <div class = "status">
     <div class="status__text leaved">
        <p>Most ancient</p>
    </div>
     <div class="status__text current">
        <p>Most recent</p>
        <span id="pad">.</span>
    </div>
    </div>
</header>

app/views/shared/_popup.html.erb
<div class="popup" id="popup">
<div class="closs">
<i class="fa-solid fa-xmark"></i>
</div>
    <div class="popup_link">
        <%= link_to 'Categories' %>
        <%= link_to 'New category', new_group_path %>
        <%= link_to 'Login', new_user_session_path  %>
        <%= link_to 'Logout',  destroy_user_session_path, data: { turbo_method: :delete }  %>
    </div>
</div>

app/views/users/slash.html.erb
<div class="slash_container">
<p class="app__name">Budget trucker</p>
<div class="links">
    <p class="active"><%= link_to 'Login', new_user_session_path %></p>
    <p ><%= link_to 'Sign Up', new_user_registration_path %></p>
</div>
</div>